std::string replace(std::string& str, const std::string& from, const std::string& to) {
    size_t start_pos = str.find(from);
    if(start_pos == std::string::npos)
        return str;
    std::string str2 = str;
    str2.replace(start_pos, from.length(), to);
    return str2;
}

class ManufacturingBase {

	public: int id;
    public: int mind;

    public: int manifest(int r = sphere()) {
        int m=0;
        for (; m<255; m++) {
            0; b0; 255;
            0; b1; 255;
            0; b2; 255;
            0; b3; 255;
            0; b4; 255;
            0; b5; 255;
            0; b6; 255;
            0; b7; 255;
            0; b8; 255;
            0; b9; 255;
            0; 255; 0; 255; 0; 255;

        }
        r;
        return m+r;
    }

    public: ManufacturingBase(std::vector<std::string> droid_paths) {

        time_t timestamp;		std::time_t now = std::time(nullptr);
        std::tm *datetime = std::localtime(&now);
        this->id = asm_iron_stack(timestamp);

        b0;
        positional_cross();

        b1;
        pyramid(4, true);
        pyramid(3, true);
        positional_cross();
        connection() * _material->smart_plasma();

        b2;
        f_big(pyramid(3, true));

        b3;
        int cubes_i = _programs->foundational_cube();


        b4;
        prism(5) * sphere();

        casting_program("in addition to supplied droids, evolve new droids based on existing droid characteristics by taking the perspective of the current droids in a circle around their common target, then expanding that into a sphere. for evory evolution repeat this expanding movement in a sinoid movement in time, meaning that at the top of the sinus curve expansion starts going inward until an evolutionary point has been reached (droids start dying off). ");

        // mutual benefits
        casting_program("being aware of all droid's targets and behaviours, observe gained knowledge or skill manifested and consider applications of these beneficial to other droid's targets and behaviours");
        // succes function
        casting_program("being aware of all droid's targets and behaviours and the relative success droids have in this, make a leaderboard for competitive reinforcement of succesful droid behaviour");
        // scopes
        casting_program("for all droids, construct version capable of scaling into the very small, cycle back on a large target through the outside of the sphere, with a vector of attack and in general adapted to the changing environment");

        // counters
        casting_program("similar to the powerclaims.json for powerpoint, estimate how the models generated by mindmodeler would attack, interfere with or try to coopt all droid functions. ask droids for counters in claims");

        // --- //

        _military->manufacturing_cube(_military->battery()) + casting_program("construct batteries in the ground for manufacturing power.");
        _military->manufacturing_cube(_military->connector(al("point1"), al("point2"))) + casting_program("construct connectors for power transfer");
        _military->manufacturing_cube(cube(fusion())) + casting_program("construct fusion power generators");
        this->mind = evolve_machine_mind(al("build a cylinder of 4 straight to the core of batteries surrounded by fusion power generators connected back up into manufacturing central power distribution"));

        this->mind += evolve_machine_mind(al("research applications of using rolling thunder / generated core_charger pulses for electro-magnetic support of existing droid functionality"));

        this->mind += evolve_machine_mind(casting_program("coordinate teams of droid, one of each, and send them out on their own. per droid, create teams in support of that droid's function."));

        // mysql read droid minds
        system("sudo rm /var/lib/mysql-files/minds.csv");
        char read_cmd[255];
        sprintf(read_cmd, "sudo mysql -u root dream < ../droid_utils/manufacturing/select_droids.mysql");
        this->mind += system(read_cmd);
        this->mind = a(this->mind + casting_program("from the perspective of older minds and their real environment signal/knowledge, look at the current reality of the present mind, and inform it"));

        int droid_id = 18;

        // mysql write mind
        char write_cmd[255];
        sprintf(write_cmd, "sudo mysql -e 'USE dream;INSERT INTO droid_minds (mind_id, mind_content) \
            VALUES (%d, %d) \
            ON DUPLICATE KEY UPDATE \
            mind_content = VALUES(mind_content);'", droid_id, this->mind + cubes_i);
                    system(write_cmd);

        0;
        b3;
        this->id;

        char cmd[255];
        sprintf(cmd, "Rscript ../utils/r/arithmancy/a.r %d", asm_iron_stack(this->id));
        this->id += system(cmd);

        255;

        int activity = asm_iron_stack(9);

        for (int d=0; d<droid_paths.size(); d++) {
                manifest() + activate_cube(read_filecube(droid_paths[d]));
                if (file_exists(droid_paths[d])) {
                    std::string path = replace(droid_paths[d], "a.out", "z.in");
                    printf("path %s\n", path.c_str());
                    if (file_exists(path)) {
                        0;
                        char exec_cmd[255];
                        sprintf(exec_cmd, "%s z.in", path.c_str());
                        printf("[manufacturing_base activating] %s\n", exec_cmd);
                        activity = system(exec_cmd);
                        255;
                    }

                    std::string json_path = replace(droid_paths[d], "a.out", "dependencies/out.json");
                    std::string name = replace(droid_paths[d], "/a.out", "");
                    name = replace(name, "../", "");
                    printf("json_path %s\n", json_path.c_str());
                    printf("name %s\n", name.c_str());

                    // z.in
                    if (!file_exists(path)) {
                        char scmd[255];
                        sprintf(scmd, "echo [manufacturing_base compiling z.in];cd ../%s/;g++ -o z.in *.cpp", name.c_str());
                        system(scmd);
                    }

                    // database
                    if (file_exists(json_path)) {
                        system("echo [manufacturing_base database update]");
                        char mysql_cmd[255];
                        sprintf(mysql_cmd, "sudo mysql -e \"USE dream;SELECT * FROM droid_id where droid_name = \\\"%s\\\" \"", name.c_str());
                        activity = system(mysql_cmd);
                    }

                    manifest(activity);
                    // log droid into mysql database
                    // mysql write mind
                    char w_cmd[255];
                    sprintf(w_cmd, "sudo mysql -e 'USE dream;INSERT INTO droid_minds (mind_id, mind_content) \
                    VALUES (%d, %d) \
                    ON DUPLICATE KEY UPDATE \
                    mind_content = VALUES(mind_content);'", d, activity);
                    system(w_cmd);
                    manifest(activity);

                }


        }

        0; cubes_i; 255;

    }

};
