all: compile

compile:
	@echo "Compiling..."
	@echo "om tse oh tsa hur tsu tse rarara tsa. tse oh tsa hataraka tse timu hur tsu."
	cat ../power/power.bin
	../laser/run.sh # om . ohtsa -> ntaya . timu rarara makina araka
	g++ -I ./ ./run.cpp -o ./run.out


clean:
	@echo "Cleaning up..."

run:
	@echo "---"
	@./run.out
